### ISSUE TITLE
Support for recursive delete (rmr)

### ISSUE THREAD

**Issue by devoncrouse** [yfinkelstein/node-zookeeper#92] opened 2013-09-22 23:04 UTC
Added in 3.4.0; note, in 3.5+ it will change from 'rmr' to 'deleteall':
https://issues.apache.org/jira/browse/ZOOKEEPER-729

**Comment by DavidVujic** [comment] 2019-03-07 21:29
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:29 UTC
Labels: feature-request
