### ISSUE TITLE
SASL/Kerberos support

### ISSUE THREAD

**Issue by cstigler** [yfinkelstein/node-zookeeper#128] opened 2016-09-09 00:15 UTC
Will this library support connections to Zookeeper using SASL and Kerberos/NTLM? I can't find any info on this.

If that's not currently possible, is it likely to be added soon? Or would love to hear your thoughts on how feasible it would be for us to add that kind of functionality in a PR, and what the best strategy to do so might be.

Thank you for the library, and your time!

**Comment by mdlavin** [comment] 2016-09-09 12:13
I haven't looked into what it would take to add SASL and Kerberos/NTLM
support. But, if you wanted to give implementing it a shot, I'd be happy to
review and give advice if you run into trouble.

**Comment by cstigler** [comment] 2016-09-09 20:53
Thank you for the fast reply! Will definitely look into it when we hit that point, and let you know if we get anywhere.

**Comment by DavidVujic** [comment] 2019-03-07 21:31
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:31 UTC
Labels: feature-request
