### ISSUE TITLE
Event `connect` triggered twice

### ISSUE THREAD

**Issue by yefremov** [yfinkelstein/node-zookeeper#87] opened 2013-04-07 17:48 UTC
When `ZooKeeper.init()` is called, event `connect` triggered twice, instead of calling event `connecting` while connecting and `connect` when connected.

**Comment by DavidVujic** [comment] 2019-03-07 21:29
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:29 UTC
Labels: bug
