### ISSUE TITLE
when zk server died, An error has been created

### ISSUE THREAD

**Issue by yqsailor** [yfinkelstein/node-zookeeper#139] opened 2017-07-18 06:07 UTC
when zk server died, An error has been created， the error is:

2017-07-18 14:03:52,370:5928:ZOO_ERROR@handle_socket_error_msg@1748: Socket [127.0.0.1:2181] zk retcode=-4, errno=61(Connection refused): failed while receiving a server response
zk node create rc: -4, error: connection loss, path=null
2017-07-18 14:03:52,372:5928:ZOO_ERROR@zk_io_cb@322: yield:zookeeper_process returned error: -4 - connection loss

I want catch this error and reconnect the zk server, what should i do? thanks for first!

**Comment by kuebk** [comment] 2017-07-19 15:09
You should add listeners for other connection-oriented events, like on_connecting, on_closed.

**Comment by Sailor20** [comment] 2017-07-21 05:41
I had added the listeners, but it do not work!

![Uploading zookeeper-error.png…]()

**Comment by kuebk** [comment] 2017-07-24 10:10
You missed the ```on_connecting``` event.

**Comment by Sailor20** [comment] 2017-09-01 03:36
@kuebk the on_connecting event  is monitor the connecting event,  when an error has occurred, I want monitor the error and reconnect the zk, what should I do?

**Comment by JianChuanting** [comment] 2018-03-15 03:22
@Sailor20 Do you find the way to monitor error event?

**Comment by Sailor20** [comment] 2018-03-15 08:27
@JianChuanting Sorry, I haven't solved it yet! if you find a solution, please tell me, thanks for first!

**Comment by DavidVujic** [comment] 2019-03-07 21:35
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. Maybe this relates to this PR? https://github.com/yfinkelstein/node-zookeeper/pull/96

I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:35 UTC
Labels: question
