### ISSUE TITLE
The service runs for a long time， the watch_cb of the aw_get_children cannot work

### ISSUE THREAD

**Issue by yqsailor** [yfinkelstein/node-zookeeper#140] opened 2017-09-01 03:40 UTC
The service runs for a long time， the watch_cb of the aw_get_children cannot work, what should i do?

thanks for first!

**Comment by DavidVujic** [comment] 2019-03-07 21:38
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. 

I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:38 UTC
