### ISSUE TITLE
callback not invoked for invalid arguments

### ISSUE THREAD

**Issue by mlin** [yfinkelstein/node-zookeeper#44] opened 2012-03-30 00:59 UTC
If you pass null or undefined for pathname arguments (not a rare inadvertent occurrence when developing Node.js code), the callback is not invoked, nor is an error event fired. This is surprising behavior.

```
var ZooKeeper = require('zookeeper');
var zk = new ZooKeeper({connect: "localhost:2181"});
zk.on('error', function() { console.log('Got an error!'); });
zk.connect(function (err) {
  if(err) console.log('Got an error!');
  console.log('About to try something silly...');
  zk.a_create(null, 'data', ZooKeeper.ZOO_PERSISTENT, function(rc,err,path) {
    console.log('Got a callback!');
  });
});
```

This prints only 'About to try something silly...'

**Comment by DavidVujic** [comment] 2019-03-07 21:27
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:27 UTC
Labels: bug
