### ISSUE TITLE
callback not executed when connect failed

### ISSUE THREAD

**Issue by freedaxin** [yfinkelstein/node-zookeeper#55] opened 2012-05-09 10:55 UTC
when an unreachable address is given to config, the callback will not be executed. 
is it expected? 
how can I know the failure?

**Comment by malpiatko** [comment] 2017-07-14 00:49
what is the correct course of action here?

**Comment by DavidVujic** [comment] 2019-03-07 21:28
I'm closing this one. Please create a new issue (or a PR) if you think it is a mistake and the issue is still relevant. I am a new maintainer and would be very happy for feedback and contributions!

**Closed by DavidVujic** 2019-03-07 21:28 UTC
Labels: bug
